[package]
name = "nightcycle/format"
description = "why learn basic xml when you can instead just type like you're using discord"
version = "0.1.1"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
string = "nightcycle/string@0.1.0"
coldfusion = "nightcycle/cold-fusion@1.0.1"
signal = "quenty/signal@^2.0.0-canary"
maid = "quenty/maid@^2.0.1-canary"
